const originalNames = [
  "images/Alejandro Garnacho.jpeg",
  "images/Alessandro del piero.jpeg",
  "images/andreas Pereira).jpeg",
  "images/Ange Postecoglou.jpeg",
  "images/arda guler.jpeg",
  "images/beckham.jpeg",
  "images/bellerin.jpeg",
  "images/bellingham.jpeg",
  "images/bruno fernandes.jpeg",
  "images/Carlos Puyol.jpeg",
  "images/COLD PALMER.jpeg",
  "images/cristiano ronaldo.jpeg",
  "images/David Healy.jpeg",
  "images/david silva.jpeg",
  "images/de jong.jpeg",
  "images/dybala.jpeg",
  "images/Edwin van der Sar.jpeg",
  "images/enzo fernandes.jpeg",
  "images/Eusebio Portugalia.jpeg",
  "images/falcao.jpeg",
  "images/fernando torres.jpeg",
  "images/Frank Lampard.jpeg",
  "images/Gabriel Jesus jpeg",
  "images/Garrincha.jpeg",
  "images/Gennaro Gattuso.jpeg",
  "images/george best.jpeg",
  "images/Grealish .jpeg",
  "images/greenwood.jpeg",
  "images/Hulk.jpeg",
  "images/Hull.jpeg",
  "images/Ibou Konate.jpeg",
  "images/imobille.jpeg",
  "images/Iñigo Martínez.jpeg",
  "images/isak.jpeg",
  "images/Jasper Cillessen.jpeg",
  "images/Ji-Sung Park.jpeg",
  "images/Jordan Henderson.jpeg",
  "images/Julian Draxler.jpeg",
  "images/kaka.jpeg",
  "images/Kylian Mbappe.jpeg",
  "images/Lamine Yamal.jpeg",
  "images/Lautaro Martinez.jpeg",
  "images/lewandowsky.jpeg",
  "images/Luis Diaz.jpeg",
  "images/Benjamin Sesko.jpeg",
  "images/Mathias De Ligt.jpeg",
  "images/Mauro Icardi .jpeg",
  "images/Michael Bradley.jpeg",
  "images/naingolan.jpeg",
  "images/Nemanja Vidic.jpeg",
  "images/nesta.jpeg",
  "images/nico williams.jpeg",
  "images/Olivier Giroud.jpeg",
  "images/Oscar.jpeg",
  "images/ozil.jpeg",
  "images/Paolo Maldini.jpeg",
  "images/Peter Schmeichel jpeg",
  "images/Pirlo.jpeg",
  "images/pulisic.jpeg",
  "images/Radamel Falcaor.jpeg",
  "images/Richard Rios.jpeg",
  "images/Rob Witschge.jpeg",
  "images/Robin van Persie.jpeg",
  "images/robinho.jpeg",
  "images/romero barca.jpeg",
  "images/romero tottenham.jpeg",
  "images/Rooney.jpeg",
  "images/Ruben Amorim.jpeg",
  "images/Ruben Neves.jpeg",
  "images/saka.jpeg",
  "images/scholes.jpeg",
  "images/havertz.jpeg",
  "images/Solanke.jpeg",
  "images/Lucas Ribeiro .jpeg",
  "images/talisca.jpeg",
  "images/vidic.jpeg",
  "images/Vinicius 7.jpeg",
  "images/werner.jpeg",
  "images/Martial.jpeg",
];
const fullNames = [
  "Alejandro Garnacho",
  "Alessandro Del Piero",
  "Andreas Pereira",
  "Ange Postecoglou",
  "Arda Güler",
  "David Beckham",
  "Héctor Bellerín",
  "Jude Bellingham",
  "Bruno Fernandes",
  "Carlos Puyol",
  "Cole Palmer",
  "Cristiano Ronaldo",
  "David Healy",
  "David Silva",
  "Frenkie de Jong",
  "Paulo Dybala",
  "Edwin van der Sar",
  "Enzo Fernández",
  "Eusébio Portugal",
  "Radamel Falcao",
  "Fernando Torres",
  "Frank Lampard",
  "Gabriel Jesus",
  "Garrincha",
  "Gennaro Gattuso",
  "George Best",
  "Jack Grealish",
  "Mason Greenwood",
  "Hulk",
  "Hull",
  "Ibrahima Konaté",
  "Ciro Immobile",
  "Iñigo Martínez",
  "Alexander Isak",
  "Jasper Cillessen",
  "Ji-Sung Park",
  "Jordan Henderson",
  "Julian Draxler",
  "Kaká",
  "Kylian Mbappé",
  "Lamine Yamal",
  "Lautaro Martínez",
  "Robert Lewandowski",
  "Luis Díaz",
  "Benjamin Šeško",
  "Matthijs de Ligt",
  "Mauro Icardi",
  "Michael Bradley",
  "Radja Nainggolan",
  "Nemanja Vidić",
  "Alessandro Nesta",
  "Nico Williams",
  "Olivier Giroud",
  "Oscar",
  "Mesut Özil",
  "Paolo Maldini",
  "Peter Schmeichel",
  "Andrea Pirlo",
  "Christian Pulisic",
  "Radamel Falcao",
  "Richard Rios",
  "Rob Witschge",
  "Robin van Persie",
  "Robinho",
  "Cristian Romero (Barcelona)",
  "Cristian Romero (Tottenham)",
  "Wayne Rooney",
  "Rúben Amorim",
  "Rúben Neves",
  "Bukayo Saka",
  "Paul Scholes",
  "Kai Havertz",
  "Dominic Solanke",
  "Lucas Ribeiro",
  "Anderson Talisca",
  "Nemanja Vidić",
  "Vinícius Júnior",
  "Timo Werner",
  "Anthony Martial",
];
